name: Missing Shader Instruction
description: Shader Instruction is missing in Trijinx.
title: "[GPU]"
labels: [gpu, not-implemented]
body:
  - type: textarea
    id: instruction
    attributes:
      label: Shader instruction
      description: What shader instruction is missing?
    validations:
      required: true
  - type: textarea
    id: required
    attributes:
      label: Required by
      description: Add links to the [compatibility list page(s)](https://github.com/Trijinx/Trijinx-Games-List/issues) of the game(s) that require this instruction.
    validations:
      required: true
